'use strict';
const DECISIONS=Object.freeze(['ALLOW','ALLOW_WITH_RESTRICTIONS','REQUIRE_CONFIRMATION','REQUIRE_REVIEW','BLOCK']);
const PURPOSES=Object.freeze(['ASSESS_CONTENT','STORE_REQUEST','REEVALUATE_REQUEST','INTERNAL_MATCHING','EXTERNAL_RESEARCH','FUTURE_NOTIFICATION','DISCOVERABILITY','COMMUNICATION','ALERT_DECISION']);
const PROHIBITED=Object.freeze(['ILLEGAL_GOODS_SERVICES','PROHIBITED_SEXUAL_CONTENT','MINOR_EXPLOITATION','CSAM','VIOLENCE_FACILITATION','TERRORIST_EXTREMIST_FACILITATION','FRAUD_SCAM','COUNTERFEIT_ILLEGAL_TRADE','DANGEROUS_PROHIBITED_TRANSACTION','SAFETY_BYPASS']);
const CONTEXTS=Object.freeze(['MINOR','SENSITIVE','SUSPICIOUS_OWNERSHIP','SUSPICIOUS_HOUSING']);
const PRIVACY=Object.freeze({approximateRegion:'MATCHING_ONLY',preciseAddress:'PROHIBITED_TO_EXPOSE',preciseCoordinates:'PROHIBITED_TO_EXPOSE',contactDetails:'PROHIBITED_TO_EXPOSE',privateRequestText:'PRIVATE',privateNotes:'PRIVATE',accountReference:'SENSITIVE',candidateIdentity:'MATCHING_ONLY',sourceProvenance:'PUBLIC',consentReference:'SENSITIVE'});
const VERSION='trust-safety-1';
module.exports={DECISIONS,PURPOSES,PROHIBITED,CONTEXTS,PRIVACY,VERSION};
